spring.application.name=carepulse-backend

server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/carepulse
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.indent-output=true

logging.file.name=logs/carepulse.log

logging.level.root=INFO
logging.level.com.carepulse=DEBUG

debug=true